### ISSUE TITLE
not enough memory 

### ISSUE THREAD

**Issue by glaudelrio** [devillemereuil/bayescenv#10]
Hi I am facing an error with bayescenv...

My Verif file only has these lines: 

`"Summary of parameters and input files.
Please check that all is correct while calculation is starting...
There are 15947776 loci.
There are 2 populations."`

There is no error message. And the log file only says:

`"This is BayeScEnv version 1.1.
Using 20 threads (20 cpu detected on this machine)
Not enough memory for pop[0].locus"`

and the program exits right after this.

.sel program is empty
and .Fst is not generated.

I imagine there is something to do with the number of SNPs in my input, which is big because I am dealing with bird whole genomes.

Thank you so much for any help!!!
Best wishes

**Comment by glaudelrio** [comment]
I tested the program with available dataset, and everything worked fine.

Here is the command I ran with my data:

`bayescenv /bayescenv-1.1/input_bayescan_mt.txt -env /bayescenv-1.1/mt_env.txt -od /bayescenv-1.1/ -o mt_LongRun -n 5000 -thin 10 -nbp 20 -pilot 5000 -burn 50000 -pr_jump 0.1 -pr_pref 0.5`

Thank you!!!

**Comment by devillemereuil** [comment]
Hi,

Unfortunately, there is not such much I can do on BayeScEnv's side, even if a professional programmer stepped in to include more aggressive memory handling in the software, I think the gain would be marginal (in the sense that it would not be using say 50% less memory...).

How much RAM has the computer you are running the software on? With this much data, you would need a large amount of memory (probably above 64Gb, but it is difficult to guesstimate...).

A possible workaround is to prune your data and remove many SNPs that I would expect to be in strong linkage (?), as linked loci are not informative for BayeScEnv.
