### ISSUE TITLE
How to get the Environmental data

### ISSUE THREAD

**Issue by HengLiang1993** [devillemereuil/bayescenv#11]
Hi I still do not kown how to get the Environmental data. Can you help me?

**Comment by devillemereuil** [comment]
Hi,

Please be more precise with your request. What are you missing?

**Comment by HengLiang1993** [comment]
Hi again. Sorry to bother you. I've been using the software BayeScenv you developed recently to caculate the outliers. I have get the genotyte input files.But I do not know how to get the input file Environmental values. I have the latitude and longitude about my poplation and what more data do i need？ And then how to used them to convert them to the  input file Environmental values？

**Comment by devillemereuil** [comment]
You'll need to decide on a reference point that you would consider roughly "neutral" (many would opt for the average across populations, but not necessarily). If you opt for the average, the best would be to standardise your variables (say, using the "scale()" function in R) and take the absolute values ("abs()").

**Comment by devillemereuil** [comment]
You can look here for more information :
https://github.com/devillemereuil/bayescenv/wiki/3.-Input-files#environmental-data

**Comment by HengLiang1993** [comment]
Thanks. I seemed to understand it.
