### ISSUE TITLE
q-values of 0

### ISSUE THREAD

**Issue by DevonDeRaad** [devillemereuil/bayescenv#6]
I am running bayescenv on a large SNP dataset, and manhattan plotting -log10(q-value) to visualize significance across the genome. I have now realized that my most significant SNPs are not being plotted because their q-value is 0, so the -log10 becomes infinity. I have manually converted the 0 qvalues to 1e-5, so that they will plot, but I just wanted to verify that this is not a bug, and ask what you would recommend in this case. Thanks for your time!

**Comment by devillemereuil** [comment]
A q-value will "saturate" to 0 when the Reversible Jump never chooses another model. So, all the samples comes from the same model and its posterior probability is evaluated to 1, then the PEP and q-values are computed as equal to 0.

This means the "actual" q-value is lower than (1 / Nsamp) where Nsamp is the length of your MCMC. So, if you have 1e5 iterations, then replacing these q-values to 1e-5 is reasonable.
