### ISSUE TITLE
huge data set

### ISSUE THREAD

**Issue by Huyuxi08** [devillemereuil/bayescenv#8]
Hi @devillemereuil ,

I'm currently running BayeScEnv on my WGS data, considering such a large data set (1 million sites), is it feasible to divide them into multiple subsets？
Actually I have tried with the command "-nbp 10 -pilot 2000 -thin 10 -n 5000 -burn 10000 ", but when calibrated the MCMC, I found that the results didn't reach convergence. So I increased the parameters ("-nbp 20 -pilot 5000 -thin 10 -n 5000 -burn 20000"), but it takes a very long time to run. Thus I'm wondering if I could divide my data into multiple subsets.
Thanks in advance.

Best,
yuxi Hu

**Comment by devillemereuil** [comment]
You could increase only the burn-in, instead of the whole pilot studies?

It's possible to subdivide your data in multiple datasets, but you have to keep in mind that the neutral model might then be slightly different between runs with a different datasets (i.e. neutral markers will be different).

**Comment by Huyuxi08** [comment]
Thanks so much!
